config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'dashboard#index'
  root to: 'site#index'
  resources :messages
  resources :categories
  namespace :api do
    namespace :v1 do
      resources :messages, only: %i[
        index
        create
        destroy
        update
        reply
      ] do
        collection do
          get 'reply'
        end
      end
    end
  end
end

app/models/message.rb
# frozen_string_literal: true

# Model for message objects
class Message < ApplicationRecord
  belongs_to :category
  belongs_to :user
  validates :subject, presence: true

  def self.split_paragraphs(msg)
    msg.split(/[\r\n]/).reject(&:empty?)
  end

  def self.unroll_paragraphs(paragraphs)
    return [] if paragraphs.nil? || paragraphs.empty?

    paragraphs, lastp = get_next paragraphs, nil
    plist = Array.new(1, lastp)
    until paragraphs.empty?
      paragraphs, nextp = get_next paragraphs, lastp.id
      plist.push nextp
      lastp = nextp
    end
    plist.reverse
  end

  def self.get_next(paragraphs, next_id)
    list = paragraphs.select { |p| p.next_id == next_id }
    first = list.first
    unless first.children.empty?
      first.children = unroll_paragraphs first.children
    end
    paragraphs.delete first
    [paragraphs, first]
  end

  def self.get_paragraphs(who, helpers, message, parent)
    result = []
    paragraphs = Paragraph.select { |p| by_parent p, message, parent }
    paragraphs.map do |p, count|
      seen = see_paragraph p.id, who.id
      p = format_paragraph p
      pp = ClientParagraph.new helpers, p, seen, count
      pp.children = get_paragraphs who, helpers, message, p.id
      result.push pp
    end
    result
  end

  def self.by_parent(paragraph, message, parent)
    paragraph.message_id == message && paragraph.parent_id == parent
  end

  def self.see_paragraph(paragraph, who)
    seen = Beenseen.select do |s|
      (s.paragraph_id == paragraph) && (s.user_id == who)
    end
    if seen.empty?
      see = Beenseen.new
      see.user_id = who
      see.paragraph_id = paragraph
      see.save
    end
    seen
  end

  def self.format_paragraph(paragraph)
    return if paragraph.nil?

    mark = initialize_formatting
    if paragraph.content.starts_with?('```') ||
       paragraph.content.starts_with?('~~~')
      paragraph.content = mark.render paragraph.content
      return paragraph
    end
    if paragraph.content.starts_with? '#'
      # Demote each header
      paragraph.content = '#' + paragraph.content
    end
    content = paragraph.content
    escaped = CGI.escapeHTML content
    escaped.gsub! '&quot;', '"'
    escaped.gsub! '&#39;', "'"
    punct = RubyPants.new(escaped, 3).to_html
    html = mark.render punct
    content = html
              .sub('<p>', '')
              .reverse.sub('</p>'.dup.reverse, '')
              .reverse
    if !content.starts_with?('<code>') &&
       !content.starts_with?('<table>') &&
       !content.starts_with?(/<h[1-6]/)
      content = content
                .gsub(
                  %r{(\.|,|!|\?|:|\(|\)|&|;|/|&ndash;|&mdash;|&hellip;)}m,
                  "\n".dup.concat('\1').concat("\n")
                )
                .gsub(
                  /(<a [^<]*<[^>]*>|<[^>]*>|&[A-Za-z]*;|&\n*#[0-9]*\n*;)/
                ) do |match|
        match.gsub(/\n/) { |_inner| '' }
      end
                .split("\n")
      if paragraph.split
        if content.count == 1
          content += ' '
        else
          # It looks like we should test that the last element of
          # the array is punctuation, but since this paragraph has
          # been split, we already know it must be, so we can
          # barrel through without any test
          last = content.pop
          content[-1] += last
        end
      end
      paragraph.content = content
    else
      paragraph.content = [content]
    end
    paragraph
  end

  def self.initialize_formatting
    rend = Redcarpet::Render::HTML.new(
      escape_html: true, hard_wrap: true, prettify: true,
      safe_links_only: true, with_toc_data: true
    )
    Redcarpet::Markdown.new(rend, {
                              disable_indented_code_blocks: true,
                              fenced_code_blocks: true, footnotes: true,
                              strikethrough: true, superscript: true,
                              autolink: true, tables: true, underline: true
                            })
  end
end

# A utility class to package paragraph information for the view
class ClientParagraph
  attr_accessor :avatar
  attr_accessor :beenseen
  attr_accessor :children
  attr_accessor :content
  attr_accessor :count
  attr_accessor :created_at
  attr_accessor :id
  attr_accessor :message_id
  attr_accessor :next_id
  attr_accessor :parent_id
  attr_accessor :ts
  attr_accessor :updated_at
  attr_accessor :user_id
  attr_accessor :when
  attr_accessor :who

  def initialize(helpers, paragraph, seen, count)
    user = User.select { |u| u.id == paragraph.user_id }.first
    self.avatar = helpers.avatar 100, user
    self.beenseen = !seen.empty?
    self.content = paragraph.content
    self.count = count
    self.created_at = paragraph.created_at
    self.id = paragraph.id
    self.message_id = paragraph.message_id
    self.next_id = paragraph.next_id
    self.parent_id = paragraph.parent_id
    self.ts = paragraph.created_at.to_formatted_s(:db)
    self.updated_at = paragraph.updated_at
    self.user_id = paragraph.user_id
    self.when = helpers.time_ago_in_words(paragraph.created_at)
    self.who = user
  end
end

app/controllers/api/v1/messages_controller.rb
# frozen_string_literal: true

# API Namespace
module Api
  module V1
    # Controller for the Messages API
    class MessagesController < Api::V1::BaseController
      def index
        respond_with Message.all
      end

      def create
        respond_with :api, :v1, Message.create(message_params)
      end

      def destroy
        respond_with Message.destroy(params[:id])
      end

      def update
        message = Message.find(params['id'])
        message.update_attributes(message_params)
        respond_with message, json: message
      end

      def reply
        para_id = params[:paraId].to_i
        offset = params[:offset].to_i
        message = params[:message].strip
        punctuation = params[:punctuation]

        case punctuation
        when '–', '…'
          offset += 2
        when '—'
          offset += 1
        end

        paragraph = Paragraph.find(para_id)
        first_part = paragraph.content[0..offset].strip
        last_part = if offset < paragraph.content.length
                      paragraph.content[offset + 1..-1].strip
                    else
                      ''
                    end

        if message.empty?
          respond_with 'Reply message is empty'
          return
        end

        # Split the paragraph if the split isn't at the end
        unless last_part.empty?
          fragment = Paragraph.new
          fragment.message_id = paragraph.message_id
          fragment.next_id = paragraph.next_id
          fragment.user_id = paragraph.user_id
          fragment.parent_id = paragraph.parent_id
          fragment.content = last_part
          fragment.split = false
          fragment.save

          paragraphs = Paragraph.select do |p|
            p.parent_id == paragraph.id
          end
          paragraphs.each do |p|
            p.parent_id = fragment.id
            p.save
          end

          paragraph.next_id = fragment.id
          paragraph.content = first_part
          paragraph.split = true
          paragraph.save
        end

        rpars = Message.split_paragraphs message
        block_par = nil
        prev_par = nil
        children = []

        rpars.reverse_each do |p|
          if block_par.nil? &&
             (p.start_with?('```') ||
               p.start_with?('~~~') ||
               p.start_with?('|')
             )
            block_par = p + "\n"
          elsif (
              !block_par.nil? &&
              block_par.start_with?('`') &&
              !p.start_with?('```') &&
              !p.start_with?('~~~')
            ) || (
              !block_par.nil? &&
              block_par.start_with?('|') &&
              p.start_with?('|')
            )
            block_par += p + "\n"
          else
            # Flush the buffered table
            if !block_par.nil? && block_par.start_with?('|')
              block_par = block_par.split("\n").reverse.join("\n")
              par = {
                message_id: paragraph.message_id,
                parent_id: paragraph.id,
                next_id: prev_par ? prev_par.id : nil,
                user_id: current_user.id,
                content: block_par
              }
              prev_par = Paragraph.new par
              prev_par.save
              children.push prev_par
              block_par = nil
            end
            par = {}
            if p.start_with?('```') || p.start_with?('~~~')
              block_par += p + "\n"
              lines = block_par.split("\n").reverse.join("\n")
              par = {
                message_id: paragraph.message_id,
                parent_id: paragraph.id,
                next_id: prev_par ? prev_par.id : nil,
                user_id: current_user.id,
                content: lines
              }
            else
              par = {
                message_id: paragraph.message_id,
                parent_id: paragraph.id,
                next_id: prev_par ? prev_par.id : nil,
                user_id: current_user.id,
                content: p
              }
            end
            prev_par = Paragraph.new par
            prev_par.save
            children.push prev_par
            block_par = nil
          end
        end

        result = Message.get_paragraphs current_user,
                                        helpers,
                                        paragraph.message_id,
                                        nil
        result = Message.unroll_paragraphs result
        respond_with result
      end

      private

      def message_params
        params.require(:message).permit(:id, :name, :description)
      end
    end
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

require 'redcarpet'
require 'rubypants'

# The message controller
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_message, only: %i[show edit update destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all.order('created_at DESC')
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    paragraphs = Message.get_paragraphs current_user, helpers, @message.id, nil
    @paragraphs = Message.unroll_paragraphs paragraphs
  end

  # GET /messages/new
  def new
    @message = Message.new
    @categories = Category
                  .select { |c| c.of == 'message' }
                  .collect { |c| [c.name, c.id] }
  end

  # GET /messages/1/edit
  def edit; end

  # POST /messages
  # POST /messages.json
  def create
    params = message_params
    pars = Message.split_paragraphs(params[:content])
    msg = params.except(:content)
    prev_par = nil
    block_par = nil

    if pars.empty?
      respond_to do |format|
        format.html do
          redirect_to new_message_path,
                      error: 'Message text is empty.'
        end
        format.json do
          render json: ['Message text is empty'],
                 status: :unprocessable_entity
        end
      end
      return
    end

    params[:subject] = nil if params[:subject] == ''

    @message = Message.new(msg)

    respond_to do |format|
      if @message.save
        pars.reverse_each do |p|
          if block_par.nil? &&
             (p.start_with?('```') ||
               p.start_with?('~~~') ||
               p.start_with?('|')
             )
            block_par = p + "\n"
          elsif (
              !block_par.nil? &&
              block_par.start_with?('`') &&
              !p.start_with?('```') &&
              !p.start_with?('~~~')
            ) || (
              !block_par.nil? &&
              block_par.start_with?('|') &&
              p.start_with?('|')
            )
            block_par += p + "\n"
          else
            # Flush the buffered table
            if !block_par.nil? && block_par.start_with?('|')
              block_par = block_par.split("\n").reverse.join("\n")
              par = {
                message_id: @message.id,
                parent_id: nil,
                next_id: prev_par ? prev_par.id : nil,
                user_id: @message.user_id,
                content: block_par
              }
              prev_par = Paragraph.create_new(par)
              if prev_par.save
                Rails.logger.debug('Paragraph was successfully created.')
              else
                Rails.logger.warn(prev_par.errors.to_yaml)
              end
              block_par = nil
            end
            par = {}
            if p.start_with?('```') || p.start_with?('~~~')
              block_par += p + "\n"
              lines = block_par.split("\n").reverse.join("\n")
              par = {
                message_id: @message.id,
                parent_id: nil,
                next_id: prev_par ? prev_par.id : nil,
                user_id: @message.user_id,
                content: lines
              }
            else
              par = {
                message_id: @message.id,
                parent_id: nil,
                next_id: prev_par ? prev_par.id : nil,
                user_id: @message.user_id,
                content: p
              }
            end
            prev_par = Paragraph.create_new(par)
            if prev_par.save
              Rails.logger.debug('Paragraph was successfully created.')
            else
              Rails.logger.warn(prev_par.errors.to_yaml)
            end
            block_par = nil
          end
        end

        format.html do
          redirect_to @message,
                      notice: 'Message was successfully created.'
        end
        format.json do
          render :show,
                 status: :created,
                 location: @message
        end
      else
        @message = Message.new
        @content = pars.join("\n")
        @categories = Category
                      .select { |c| c.of == 'message' }
                      .collect { |c| [c.name, c.id] }
        format.html { render :new, notice: @message.errors }
        format.json do
          render json: @message.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html do
          redirect_to @message,
                      notice: 'Message was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json do
          render json: @message.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    delete_paragraphs @message.id
    @message.destroy
    respond_to do |format|
      format.html do
        redirect_to messages_url,
                    notice: 'Message was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def reply
    format.json { head :no_content, status: :ok }
  end

  private

  def delete_paragraphs(message, parent = nil)
    ps = sort_paragraph(Paragraph.select do |p|
      (p.message_id == message) && (p.parent_id == parent)
    end)
    ps.each do |p|
      delete_paragraphs message, p.id
      Beenseen.select { |b| b.paragraph_id == p.id }.each(&:destroy)
      p.destroy
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def message_params
    params
      .require(:message)
      .permit(
        :subject,
        :content,
        :version,
        :user_id,
        :category_id
      )
  end

  def sort_paragraph(pars, _start = nil, found = [])
    return found if pars.empty?

    which = nil
    until pars.empty?
      pars.each_index do |i|
        next unless pars[i].next_id == which

        p = pars.delete_at(i)
        which = p.id
        found.unshift(p)
        break
      end
    end
    found
  end
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

# Helper functions for message objects
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label for="subject"><font size="1"><b>Subject:</b></font></label>
  <%= text_field 'message', 'subject', :value => @subject %><br>
  <% if message.id.nil? %>
    <%= text_area 'message', 'content', :value => @content, :cols => 80, :rows => 25 %><br>
  <% else %>
    <p>
      Because the structure of your original post is used as
      the structure for the conversation, you may not rewrite
      the post.  Instead, you can modify a paragraph that has
      not yet been replied to or&mdash;preferably&mdash; you
      can reply to your original message explaining the
      correction.
    </p>
  <% end %>
  <%= hidden_field 'message', 'version', :value => @version || 1 %>
  <%= hidden_field 'message', 'user_id', :value => warden.user.id %>
  <label for="category_id"><b>Category:</b></label>
  <%= select 'message', 'category_id', @categories %><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
var simplemde = new SimpleMDE({
  forceSync: true,
  placeholder: "Type here, using Markdown (not HTML) for formatting...",
  showIcons: [
    "clean-block",
    "code",
    "heading-2",
    "heading-3",
    "horizontal-rule",
    "strikethrough",
    "table"
  ],
});
</script>

app/views/messages/edit.html.erb
<h1>Editing <%= @message.subject %></h1>

<% @subject = @message.subject %>
<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th colspan="<%= current_user.nil? ? 1 : 3 %>"></th>
    </tr>
  </thead>

  <tbody>
    <% user_id = current_user.nil? ? -1 : current_user.id %>
    <% @messages.each do |message| %>
      <tr>
        <td>
          <b><%= link_to message.subject, message %><b>
        </td>
        <td class="avatar-column">
          <% user = User.find_by_id message.user_id %>
          <%= image_tag avatar(16, user), :alt => user.login, :title => user.login %>
        </td>
        <% if !current_user.nil? %>
        <td class="button-column">
          <% if user_id == message.user_id %>
            <%= link_to 'Edit', edit_message_path(message) %>
          <% end %>
        </td>
        <td class="button-column">
          <% if user_id == message.user_id %>
            <%= link_to 'Delete', message, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<div class="intro-text">
  <%= render 'form', message: @message %>

  <%= link_to 'Back', messages_path %>
</div>

app/views/messages/show.html.erb
<script type="text/javascript">
function toggleReplyForm(e) {
  e.persist();
  var target = e.target;

  while (target.tagName.toLowerCase() !== 'a') {
    target = target.parentNode;
  }

  var id = target.attributes.name.value;
  var formId = `reply-form-${id}`;
  var form = document.getElementById(formId);
  var textarea = document.querySelector(`#${formId} textarea`);

  if (form === null) {
    console.log(`can't find ${formId}`);
    return;
  }

  var state = form.style.display;

  if (state === 'block') {
    form.style.display = 'none';
    target.classList.remove('toggled-punctuation-button');
    target.classList.add('punctuation-button');
  } else {
    form.style.display = 'block';
    textarea.focus();
    target.classList.remove('punctuation-button');
    target.classList.add('toggled-punctuation-button');
  }
}

function submitReply(e, callback, reportError) {
  e.persist();
  var target = e.target;
  var offset = Number(target.attributes.offset.value);
  var paraId = Number(target.attributes.pid.value);
  var parent = target.parentNode;
  var textarea = parent.childNodes[1];
  var form = parent.parentNode;
  var linkName = form.attributes.id.value.replace('reply-form-', '');
  var matches = document.getElementsByName(linkName);
  var puncBtn = matches[0];
  var punctuation = encodeURIComponent(puncBtn.firstChild.innerText);
  var message = encodeURIComponent(textarea.value);
  var request = new XMLHttpRequest();
  var url = `/api/v1/messages/reply?paraId=${paraId}&offset=${offset}&message=${message}&punctuation=${punctuation}`;

  request.open(
    'GET',
    url,
    true
  );
  request.onload = function() {
    if (this.status >= 200 && this.status < 400) {
      var resp = this.response;

      form.style.display = 'none';
      puncBtn.classList.remove('toggled-punctuation-button');
      puncBtn.classList.add('punctuation-button');
      textarea.value = '';
      callback(reportError, resp);
    } else {
      reportError(this.response);
    }
  };

  request.onerror = function() {
    reportError('There was a connection error.');
  };

  request.send();
}
</script>

<p id="notice"><%= notice %></p>

<h2><%= @message.subject %></h2>

<h3>Category: <%= Category.find_by_id(@message.category_id).name %></h3>

<h4>Author: <%= User.find_by_id(@message.user_id).login %></h4>

<%= react_component 'Message', paragraphs: @paragraphs %>

<p class="intro-text">
  <%= link_to 'Edit', edit_message_path(@message) %> |
  <%= link_to 'Back', messages_path %>
</p>