config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'dashboard#index'
  root to: 'site#index'
  resources :messages
  resources :categories
  namespace :api do
    namespace :v1 do
      resources :messages, only: %i[
        index
        create
        destroy
        update
        reply
      ] do
        collection do
          get 'reply'
        end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bicker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="/images/bickie.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
      <div class="container-fluid">
        <div class="container logo">
          <a href="/">
            <img
              src="/images/Bicker-logo.svg"
              style="height: 1em;"
            >
          </a>
        </div>
        <div class="container">
          <div class="navbar-header">
            <!--
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            -->
          </div>
        </div>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a
            href="#"
            class="dropdown-toggle"
            data-toggle="dropdown"
            role="button"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Contents
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Categories", categories_url %></li>
            <li><%= link_to "Messages", messages_url %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a
            href="#"
            class="dropdown-toggle"
            data-toggle="dropdown"
            role="button"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Profile
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to "Edit profile", edit_user_registration_path %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
            <% if user_signed_in? %>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to "Logout",
                  destroy_user_session_path,
                  method: :delete
                %>
              </li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown avatar">
          <%= link_to image_tag(avatar.dup),
            edit_user_registration_path,
            :title => current_user.nil? ? '' : current_user.login
          %>
        </li>
      </ul>
    </nav>

    <div class="main-panel">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>